# Generated by Django 4.2.6 on 2023-11-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_book_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
